# Site settings
title: Aman Virmani
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Aman Virmani
user_description: I am a Robotics Engineer, currently in my 1st year of M.Eng. in Robotics at University of Maryland. Lately I have been immersed in computer vision research in action recognition in videos. I am also involved in a research project that aims to enhance the collaboration between multiple AI agents to collectively achieve a set task. I am currently looking for Summer 2020 internship positions in the field of robotics perception, planning and control. I have a good command on deep learning and computer vision fundamentals and have implemented a variety of deep learning networks as well.
user_title: Robotics Engineer
email: aman.virmani26@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-157375665-1"

exclude: ['package.json', 'src' , 'node_modules']
